# Doc: https://docs.microsoft.com/en-us/azure/container-instances/container-instances-github-action

name: container

on:
  push:
    branches:
      - 'main'
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-20.04
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build -f ./NodeChrome/docker-selenium-chisel.dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/docker-selenium-chisel:1.7.7-4.4.0-20220831-${{ github.sha }} ./NodeChrome/
            docker tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/docker-selenium-chisel:1.7.7-4.4.0-20220831-${{ github.sha }} ${{ secrets.REGISTRY_LOGIN_SERVER }}/docker-selenium-chisel:1.7.7-4.4.0-20220831
            docker push --all-tags ${{ secrets.REGISTRY_LOGIN_SERVER }}/docker-selenium-chisel